---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      shell: sudo docker pull devdattdatar/calculator-devops
      tag: latest
      pull: always
      
    - name: Create & Start Calculator Docker Container
      shell: sudo docker run -itd --name calculator-1 devdattdatar/calculator-devops && sudo docker start -a -i calculator-1
