---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull devdattdatar/calculator-5

    - name: running container
      shell: docker run -it -d devdattdatar/calculator-5 /bin/bash
